my_string = "Hello World"
print(my_string[0])
print(my_string[-2])
print(my_string[-3])
my_string="abcdefghi"
print(my_string)
print(my_string[2:])
print(my_string[:3])
print(my_string)
print(my_string[3:6])
print(my_string[1:3])
print(my_string[::])
print(my_string[::3])
print(my_string[2:7:2])
print(my_string[::-1])